### ISSUE TITLE
(Missing option/feature) Fetch .json url multiple times while typing

### ISSUE THREAD

**Issue by dahogenelst** [tr42/redactor-mentions#12]
On 80% completion of making a simlilar - more clunky - solution, I came across this redactor plugin. Nice work man, looks really tight. No large 3rd party dependencies or anything, just neatly coded by your lonesome. Although all my words of praise, in my opinion there is a major feature missing.

Why is data only loaded in once? If I want to mention one of 4000 users, this isn't a viable way of doing so. I need to fetch my json url every time it could be of added value. Let the business layer decide how heavy a query should be on the the system, right?

Can you give me pointers on how to implement such a feature, with an added option to let the user choose the preferred way of querying the .json url? Or are you willing to add this option to your plugin? Please let me know, I'd be happy to send you a pull request.

Thanks again for your effort!

**Comment by jasonkeene** [comment]
This plugin was written for a very specific use case.  The trade off of doing a single ajax request and then doing all the filtering locally seemed to be the right one for this use case.  Doing a separate ajax request on each keypress and having the server do the filtering seems like it would make for a worse user experience (user waiting on the callback to fire on each keypress) and would also be a lot of network noise (bad for mobile/power) and consume more resources on the server.

4000 users is not a significant amount to fetch from the server all at once.  You could cache this in memory on the server or even write it to disk periodically and have it served up statically.  That is how this plugin was intended to work.  If you need something more dynamic can you explain why you'd need this and how you'd prefer that it work?  I could see a situation where scaling this up to millions of users wouldn't work.  In that case you'd probably just need a URL per user where you'd only be fetching user data related to that users kinda like twitter does.  I'd be open to merging a feature like that and might even implement it for you if that would solve your use case.

**Comment by jufemaiz** [comment]
_like_

**Comment by jasonkeene** [comment]
@jufemaiz so you like the URL per user idea?  I was thinking about just abstracting out the user data stuff so you can just specify your own UserProvider and I'll just implement a few of them, one that grabs all the user data in one AJAX request for all redactor instances, one that grabs user data up front but per redactor instance, and one that grabs user data more dynamically based on events.  That way it would be customizable to whatever business requirements people have.

**Comment by jufemaiz** [comment]
I liked your response ;)

You want to have an idea where the caching method starts having too much overhead to be efficient and you need to shift to micro requests. I agree with you that our current requirements don't need it, and I'd be interested in seeing how other requirements would scale it up.

I think it also depends on how much data you're wanting to bring forward. The keypress method works best with low latency and tiny data chunks (ala Twitter search, Atlassian Confluence's search) and more often than not requires a cache or well indexed search to query against.

Use case needs more expansion by @dahogenelst to get an idea of the full requirements for the change to the current design :)

**Comment by dahogenelst** [comment]
@jasonkeene Thanks for your feedback. I'll try to cache the .json response so a single request will suffice. I can relate where you're coming from. I reckon you're right about 4000 people not being all that much and my requested feature does alter the user experience in a negative way. 

So, sorry for bothering you about this without having it thought through enough. Thanks again for your great plugin though!

**Comment by jasonkeene** [comment]
@dahogenelst no problem at all! I'll likely move forward with the user data provider idea so you'll at least be able to have control over this aspect of functionality without having to fork/rewrite everything.  If you run into any other issues let me know.

**Comment by dahogenelst** [comment]
Hi @jasonkeene,

I've been poking around in some client instances to assess the amount of data I need to push over the wire. Without the inclusion of the 'icon' key-value pair it already takes up around 350kb in size - bear in mind this request is still uncompressed. So I could possibly gain some performance by doing any compression, but not too much though..

Caching this request would be a logical solution, but in my situation it would be invalidated too soon. User instances get touched too much to do any sensible caching on them. Another option would be to add a dedicated timestamp which'll act as trigger to invalidate my cached json response, which I'd want to avoid as a solution, 'cause I don't like it.

Another problem I have with caching the json response as a whole is that user permissions dictate which users should be visible for the current user. To respect this ground rule, I need to cache the json response on a per-user basis. This I don't like either.

What was your initial use-case when you decided to build this plugin and what are your thoughts on my arguments above? I'd like to hear what you think.

Thanks again!

**Comment by jasonkeene** [comment]
The initial use case was for a forum software that might have multiple redactor instances on a page where we wanted a single AJAX request for all the user data once upfront to be shared by all the instances.  There would be no more than a few thousand users at most. 

Even if your user data updates frequently the only two fields this plugin uses are username and full name.  A few questions you should ask are:  How often does this data change?  If it does change frequently, would it be the end of the world to have this data stale for the duration of the cache TTL?  If caching is not an option for you, you could always maintain an in memory model of this data in something fast like redis and have this data updated async (eventually consistent) with your primary model.  If you are using a traditional relational database as your primary model you can setup triggers to update this secondary model.  That way you get the best of both worlds, fast access and the most up to date data.  Seems like a lot of work to me though :/
