### ISSUE TITLE
No example of redactor-mentions

### ISSUE THREAD

**Issue by kaivongcom** [tr42/redactor-mentions#5]
Rather than init a rails project I'm wondering if there's anything wrong in just having a folder with an example of the plug-in. It would mean myself and others could easily pull and fix problems with it. I'm happy to have a first pass at this, I just want to know if this is useful an idea or not.

Thoughts?

**Comment by yourfavorite** [comment]
Thanks Kai. Redactor is paid software so I don't think we can host that code here unfortunately.

**Comment by kaivongcom** [comment]
@yourfavorite Doh. Just found the [link to redactor](https://github.com/tr42/redactor-mentions)! Thanks for clarifying that.
